### ISSUE TITLE
Major changes

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/bids-connectivity#6]
I would like to change this website to address the BIDS Connectivity Project instead of the Workshop-only. 

  - I have started
  - changed the URL to BIDS-connectivity
  - I also changed some of the information inside the text

Some of the changes I made here do not seem to show on the website. Would it be possible to make a look please?

I changed two files:
https://github.com/PESTILLILAB/bids-connectivity/blob/main/config.toml
and
https://github.com/PESTILLILAB/bids-connectivity/blob/main/data/homepage.yml

I was trying to set a new section "#Workshops" both in the menu and header and then show the section right before the #program section, but I something is not working out.

@PeerHerholz thanks for helping!

**Comment by PeerHerholz** [comment]
Hi @francopestilli,

as discussed and organized on Friday, I'll meet with @anibalsolon today to get an intro to the website template and build process. I'll start working on the changes after that.

**Comment by PeerHerholz** [comment]
Done via #9.
