### ISSUE TITLE
Change the BIDS Connectivity Workshop Picture to BIDS Connectivity Project

### ISSUE THREAD

**Issue by francopestilli** [PESTILLILAB/bids-connectivity#7]
I would like to update the image we have now "BIDS Connectivity Workshop" To represent the new goal of the website -> "BIDS Connectivity Project"

Can you please take a look?
@PeerHerholz

**Comment by PeerHerholz** [comment]
Hi @francopestilli,

as discussed and organized on Friday, I'll meet with @anibalsolon today to get an intro to the website template and build process. I'll start working on the changes after that.

**Comment by PeerHerholz** [comment]
Done via #9.
